### PR TITLE
[1.20.1] Fixed datapack animation loading failure

### LINKED ISSUE #2312: [Bug]:  EpicFight 20.14 broke all animation assets what I imported using datapack editor for some reason
### Minecraft Version

1.20.1

### Epic Fight Version

20.14.1

### Minecraft Log Link

https://mclo.gs/G5dFi7Y

### Bug Details

So I noticed that EpicFight 20.14 broke all animation assets what I imported using datapack editor for some reason. I recorded video how it work on EF 20.13.6 and here's some logs&debug what should be when I tested with EF 20.14

[with EF 20.14](https://youtu.be/2R-ZAXVO4fo)
[with EF 20.13.6](https://youtu.be/2R-ZAXVO4fo)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Yesssssman**
Caused by a simple mistake, "/" was accidentally omitted in the conversion method, leading `NoSuchElementException`. (fixes #2312)

image

_Demonstration:_

https://github.com/user-attachments/assets/b6913dff-6f00-4029-b65c-4fc9a14341fd

Bokken, our official sample datapack, works fine.

### CODE REVIEW

File: src/main/java/yesman/epicfight/api/animation/AnimationManager.java [hunk 1]
```diff
@@ -200,9 +200,9 @@ protected void apply(List<ResourceLocation> objects, ResourceManager resourceMan
                     JsonElement jsonelement = GsonHelper.fromJson(GSON, reader, JsonElement.class);
                     this.readResourcepackAnimation(animId, jsonelement.getAsJsonObject());
                 } catch (IOException | JsonParseException | IllegalArgumentException resourceReadException) {
-                    EpicFightMod.LOGGER.error("Couldn't parse animation data from {}", animId);
+                    EpicFightMod.LOGGER.error("Couldn't parse animation data from {}", animId, resourceReadException);
                 } catch (Exception e) {
-                    EpicFightMod.LOGGER.error("Failed at constructing {}", animId);
+                    EpicFightMod.LOGGER.error("Failed at constructing {}", animId, e);
```
Comment (EchoEllet) [inline src/main/java/yesman/epicfight/api/animation/AnimationManager.java:205]: > , animId, e

We're two arguments, but there is only one `{}`?

Comment (Yesssssman) [reply src/main/java/yesman/epicfight/api/animation/AnimationManager.java:205]: Yes, I checked it prints out the stacktrace even without two brackets (This was also what IDEA recommended)

**Comment by EchoEllet** [comment]
I'm passing the build to a client to confirm the fix (will remove this comment and LGTM once I'm done).

**Review by EchoEllet — APPROVED** [review]
LGTM. @1Robert-on1 has tested and confirmed the fix.
